import { SignIn } from "@clerk/nextjs";
import Head from "next/head";
import { RootLayout } from "~/components";
import { type NextPageWithLayout } from "~/types";

const SignInPage: NextPageWithLayout = () => {

  return (
    <>
      <Head>
        <title>Home | Starters</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full basis-1/2 items-center justify-center bg-card main-height">
        <SignIn
          appearance={{
            elements: {
              formButtonPrimary: 'bg-primary hover:bg-secondary',
              card: 'clerk-container shadow-none',
              footerActionLink: 'text-secondary hover:text-primary',
              logoBox: 'hidden sm:block',
            },
          }}
        />
      </div>
    </>
  );
}

SignInPage.getLayout = (page) => {
  return <RootLayout>{page}</RootLayout>
}

export default SignInPage
