import Head from "next/head";
import { Container, RootLayout } from "~/components";
import { Skeleton } from "~/components/ui/skeleton";
import { type NextPageWithLayout } from "~/types";

const Dashboard: NextPageWithLayout = () => {

  return (
    <>
      <Head>
        <title>Dashboard | Dagashi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Container>
        <div className="space-y-4 pb-10">
          <div className="p-4 sm:p-6 lg:p-8 rounded-lg overflow-hidden">
            <div className="px-4 sm:px-6 lg:px-8 text-xl font-bold pb-4">Previous Orders</div>
            <div className="flex flex-col gap-y-4 px-4 sm:px-6 lg:px-8">
              {Array(15)
                .fill(0)
                .map((_, index) => (
                  <Skeleton className="h-24 w-full rounded-lg" key={index} />
                ))}
            </div>
          </div>
        </div>
      </Container>
    </>
  );
}

Dashboard.getLayout = (page) => {
  return <RootLayout>{page}</RootLayout>
}

export default Dashboard



