import Head from "next/head";
import { useRouter } from "next/router";
import { Container, FoodCard, RootLayout } from "~/components";
import { Button } from "~/components/ui/button";
import { type NextPageWithLayout } from "~/types";
import { api } from "~/utils/api";
import { FaArrowLeft } from "react-icons/fa6";

const RestaurantPage: NextPageWithLayout = () => {
  const router = useRouter()
  const some = router.query
  // eslint-disable-next-line @typescript-eslint/no-inferrable-types
  const id: number = Number(some?.id)
  // const foodList = api.restaurant.listFood.useQuery({ id: id })
  const restaurantDetails = api.restaurant.getRestaurantDetailsById.useQuery({ id: id })
  const newFoodList = api.food.getFoodByRestaurantId.useQuery({ id: id })
  console.log(newFoodList.data)

  return (
    <>
      <Head>
        <title>Restaurant | Dagashi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Container>
        <div className="space-y-4 pb-10">
          <div className="p-4 sm:p-6 lg:p-8 rounded-lg overflow-hidden">
            <div className="px-4 sm:px-6 lg:px-8 text-xl">
              <div className="font-bold pb-4">
                <Button variant="outline" className="mr-5" onClick={() => history.back()}><FaArrowLeft /></Button>
                {restaurantDetails.data?.name}
              </div>
              <span>{restaurantDetails.data?.tagline}</span>
              <p className="mb-5">
                {restaurantDetails.data?.address}
              </p>
            </div>
            <div className="flex max-sm:flex-col flex-wrap gap-y-4 gap-x-4 px-4 sm:px-6 lg:px-8">
              {newFoodList.data?.map((food) => (
                <FoodCard food={food} key={food.id} />
              ))}
            </div>
          </div>
        </div>
      </Container>
    </>
  );
}

RestaurantPage.getLayout = (page) => {
  return <RootLayout>{page}</RootLayout>
}

export default RestaurantPage



