import Head from "next/head";
import { Container, FoodCard, RootLayout } from "~/components";
import CategoryList from "~/components/category-list";
import { Input } from "~/components/ui/input";
import { Skeleton } from "~/components/ui/skeleton";
import { useCategoryStore } from "~/store";
import { type NextPageWithLayout } from "~/types";
import { api } from "~/utils/api";

const Home: NextPageWithLayout = () => {
  const categories = api.category.listAll.useQuery()
  const foodList = api.food.getFoodItems.useQuery()
  const { categoryName } = useCategoryStore()

  return (
    <>
      <Head>
        <title>Home | Dagashi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Container>
        <div className="space-y-4 pb-10">
          <div className="p-4 sm:p-6 lg:p-8 rounded-lg overflow-hidden">
            <Input placeholder="Find your food..." />
          </div>
          {categories.data ?
            <CategoryList categories={categories.data} />
            :
            <div className="px-4 sm:px-6 lg:px-8">
              <div className="text-xl font-bold py-3">Categories</div>
              <div className="flex w-full gap-x-4">
                {Array(4)
                  .fill(0)
                  .map((_, index) => (
                    <Skeleton className="h-28 py-1 w-20 rounded-lg" key={index} />
                  ))}
              </div>
            </div>
          }
          <div className="px-4 sm:px-6 lg:px-8 text-xl font-bold">Explore {categoryName}</div>
          {foodList?.data ?
            <div className="flex max-sm:flex-col flex-wrap gap-y-4 gap-x-4 px-4 sm:px-6 lg:px-8">
              {foodList.data.map((food) => (
                <FoodCard
                  food={food}
                  key={food.id} />
              ))}
            </div>
            :
            <div className="flex max-sm:flex-col flex-wrap gap-y-4 gap-x-4 px-4 sm:px-6 lg:px-8">
              {Array(15)
                .fill(0)
                .map((_, index) => (
                  <Skeleton className="h-44 w-full rounded-lg" key={index} />
                ))}
            </div>}
        </div>
      </Container>
    </>
  );
}

Home.getLayout = (page) => {
  return <RootLayout>{page}</RootLayout>
}

export default Home
