import Head from "next/head";
import Link from "next/link";
import { FaBox } from "react-icons/fa";
import { Container, RootLayout } from "~/components";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { type NextPageWithLayout } from "~/types";

const Home: NextPageWithLayout = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className="space-y-4 pb-10">
          <div className="p-4 sm:p-6 lg:p-8 rounded-lg overflow-hidden">
            <Input />
            <div>
              Categories
            </div>
          </div>
          <div className="px-4 sm:px-6 lg:px-8 text-xl font-bold ">Explore</div>
          <div className="flex flex-col gap-y-8 px-4 sm:px-6 lg:px-8">
          </div>
        </div>
      </Container>
    </>
  );
}

Home.getLayout = (page) => {
  return <RootLayout>{page}</RootLayout>
}

export default Home

