import { Raleway } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/navigation";
import { BlankLayout, Container } from "~/components";
import { Button } from "~/components/ui/button";
import { type NextPageWithLayout } from "~/types";
import { cn } from "~/utils/shadcn";

export const raleway = Raleway({
  subsets: ["latin"],
  adjustFontFallback: false,
})

const Index: NextPageWithLayout = () => {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Dagashi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cn("bg-landing-page bg-center bg-cover bg-no-repeat min-h-screen h-full", raleway.className)}>
        <div className="backdrop-brightness-[0.2] p-4 sm:p-6 lg:p-8 h-full min-h-screen">
          <Container>
            <div className="overflow-hidden rounded-lg flex main-height">
              <div className="m-auto text-white">
                <div className="z-50 text-6xl font-extrabold">Satisfy your cravings with <div className="md:text-outline border-[5px] border-white p-2 inline-block">Dagashi!</div></div>
                <p className="py-4 text-xl font-medium">Find the best restaurants & cafés in India</p>
                <Button className="font-bold inline-flex" onClick={() => router.push('/home')}>🍽️ Let's Go!</Button>
              </div>
            </div>
          </Container>
        </div>
      </main>
    </>
  );

}

Index.getLayout = (page) => {
  return <BlankLayout>{page}</BlankLayout>
}

export default Index
